name: botfinder
channels:
  - conda-forge
  - defaults
dependencies:
  - click=8.0.1
  - joblib=1.0.1
  - pandas=1.2.5
  - pip=21.1.3
  - python=3.9.5
  - shap=0.39.0
  - pip:
      - "--editable=git+https://github.com/JustAnotherArchivist/snscrape.git#egg=snscrape"
