name: botfinder
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.2
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - click=8.0.1
  - cloudpickle=1.6.0
  - importlib-metadata=3.10.0
  - joblib=1.0.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.1.0
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libopenblas=0.3.15
  - llvm-openmp=11.1.0
  - llvmlite=0.36.0
  - ncurses=6.2
  - numba=0.53.1
  - numexpr=2.7.3
  - numpy=1.21.0
  - openssl=1.1.1k
  - pandas=1.2.5
  - pip=21.1.3
  - python=3.9.5
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - readline=8.1
  - scikit-learn=0.24.2
  - scipy=1.7.0
  - setuptools=52.0.0
  - shap=0.39.0
  - six=1.16.0
  - slicer=0.0.7
  - sqlite=3.36.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tqdm=4.61.1
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zipp=3.4.1
  - zlib=1.2.11
  - pip:
      - "--editable=git+https://github.com/JustAnotherArchivist/snscrape.git#egg=snscrape"
